name: Release
on:
  push:
    branches:
      - develop
      - release/**

jobs:
  cascading-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.GH_TOKEN }}

      - run: |
          git fetch --prune --unshallow
          git config user.email "jacob.parish.1@gmail.com"
          git config user.name "Jacob Parish"

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.8

      - name: Install Deps
        uses: bahmutov/npm-install@v1

      - name: Perform Merge
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: node ./scripts/nextBranch
