name: Release
on:
  push:
    branches:
      - develop
      - release/**

jobs:
  cascading-merge:
    runs-on: ubuntu-latest
    env:
      github.token: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - run: git fetch --prune --unshallow

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Perform Merge
        run: node ./scripts/nextBranch
